// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/bank-accounts" | "/bank-accounts/[accountId]" | "/bank-accounts/add" | "/bank-accounts/new" | "/budget" | "/categories" | "/categories/[categoryId]" | "/categories/new" | "/credit-load" | "/credit-load/[loanId]" | "/credit-load/[loanId]/edit" | "/credit-load/add" | "/goals" | "/goals/[goalId]" | "/income" | "/investments" | "/load" | "/notifications" | "/operations" | "/operations/[operationId]" | "/operations/bars" | "/operations/trends" | "/profile" | "/recommendations" | "/recommendations/[agentId]/chat" | "/settings" | "/subscriptions" | "/total"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/bank-accounts": {}
  "/bank-accounts/[accountId]": { "accountId": string; }
  "/bank-accounts/add": {}
  "/bank-accounts/new": {}
  "/budget": {}
  "/categories": {}
  "/categories/[categoryId]": { "categoryId": string; }
  "/categories/new": {}
  "/credit-load": {}
  "/credit-load/[loanId]": { "loanId": string; }
  "/credit-load/[loanId]/edit": { "loanId": string; }
  "/credit-load/add": {}
  "/goals": {}
  "/goals/[goalId]": { "goalId": string; }
  "/income": {}
  "/investments": {}
  "/load": {}
  "/notifications": {}
  "/operations": {}
  "/operations/[operationId]": { "operationId": string; }
  "/operations/bars": {}
  "/operations/trends": {}
  "/profile": {}
  "/recommendations": {}
  "/recommendations/[agentId]/chat": { "agentId": string; }
  "/settings": {}
  "/subscriptions": {}
  "/total": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
