services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3002"
    networks:
      - web

networks:
  web:
    driver: bridge