services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_FIREBASE_VAPID_KEY: ${NEXT_PUBLIC_FIREBASE_VAPID_KEY}
    restart: unless-stopped
    ports:
      - "127.0.0.1:3002:3000"
    networks:
      - web

networks:
  web:
    driver: bridge
