export const queryKeys = {
  dashboard: ["dashboard"] as const,
  assets: ["assets"] as const,
  operations: {
    screen: ["operations", "screen"] as const,
    trends: ["operations", "trends"] as const,
    bars: ["operations", "bars"] as const,
    detail: (operationId: string) => ["operations", "detail", operationId] as const,
  },
  categories: ["categories"] as const,
  goals: ["goals"] as const,
  subscriptions: ["subscriptions"] as const,
  creditLoad: ["credit-load"] as const,
  creditLoadLoan: (loanId: string) => ["credit-load", "loan", loanId] as const,
  recommendations: ["recommendations"] as const,
  agentChat: (agentId: string) => ["recommendations", "chat", agentId] as const,
  bankAccounts: ["bank-accounts"] as const,
  bankAccountDetail: (accountId: string) => ["bank-accounts", "detail", accountId] as const,
  totalBalance: ["total-balance"] as const,
  incomeBalance: ["income-balance"] as const,
  investmentsBalance: ["investments-balance"] as const,
} as const;
