// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/bank-accounts/[accountId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank-accounts/[accountId]">> = Specific
  const handler = {} as typeof import("../../src/app/bank-accounts/[accountId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bank-accounts/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank-accounts/add">> = Specific
  const handler = {} as typeof import("../../src/app/bank-accounts/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bank-accounts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank-accounts/new">> = Specific
  const handler = {} as typeof import("../../src/app/bank-accounts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/bank-accounts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bank-accounts">> = Specific
  const handler = {} as typeof import("../../src/app/bank-accounts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/budget/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/budget">> = Specific
  const handler = {} as typeof import("../../src/app/budget/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/categories/[categoryId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/[categoryId]">> = Specific
  const handler = {} as typeof import("../../src/app/categories/[categoryId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/categories/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/new">> = Specific
  const handler = {} as typeof import("../../src/app/categories/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories">> = Specific
  const handler = {} as typeof import("../../src/app/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credit-load/[loanId]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credit-load/[loanId]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/credit-load/[loanId]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credit-load/[loanId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credit-load/[loanId]">> = Specific
  const handler = {} as typeof import("../../src/app/credit-load/[loanId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credit-load/add/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credit-load/add">> = Specific
  const handler = {} as typeof import("../../src/app/credit-load/add/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/credit-load/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credit-load">> = Specific
  const handler = {} as typeof import("../../src/app/credit-load/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/goals/[goalId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/goals/[goalId]">> = Specific
  const handler = {} as typeof import("../../src/app/goals/[goalId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/goals">> = Specific
  const handler = {} as typeof import("../../src/app/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/income/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/income">> = Specific
  const handler = {} as typeof import("../../src/app/income/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/investments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investments">> = Specific
  const handler = {} as typeof import("../../src/app/investments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/load/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/load">> = Specific
  const handler = {} as typeof import("../../src/app/load/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operations/[operationId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/[operationId]">> = Specific
  const handler = {} as typeof import("../../src/app/operations/[operationId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operations/bars/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/bars">> = Specific
  const handler = {} as typeof import("../../src/app/operations/bars/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations">> = Specific
  const handler = {} as typeof import("../../src/app/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/operations/trends/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/operations/trends">> = Specific
  const handler = {} as typeof import("../../src/app/operations/trends/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recommendations/[agentId]/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recommendations/[agentId]/chat">> = Specific
  const handler = {} as typeof import("../../src/app/recommendations/[agentId]/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/recommendations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recommendations">> = Specific
  const handler = {} as typeof import("../../src/app/recommendations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/total/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/total">> = Specific
  const handler = {} as typeof import("../../src/app/total/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
